apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: face-detection
spec:
  broker: default
  filter:
    attributes:
      type: image.png
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: pigo-service
