apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: report
spec:
  broker: default
  filter:
    attributes:
      type: emotion
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: report-service
