apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: image-extractor
spec:
  broker: default
  filter:
    attributes:
      type: boundingbox
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: image-extractor-service
