apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: yolo
spec:
  broker: default
  filter:
    attributes:
      type: image.png
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: yolo-service
