apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-extractor
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: image-extractor
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: image-extractor
          image: gcr.io/{{PROJECT_ID}}/image-extractor:{{VERSION}}
          env:
            - name: DEST
              value: "gs://aerobic-botany-270918/processed"

---

# Service pointing at the previous Deployment. This will be the target for event
# consumption.
  kind: Service
  apiVersion: v1
  metadata:
    name: image-extractor-service
  spec:
    selector:
      app: image-extractor
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

