apiVersion: apps/v1
kind: Deployment
metadata:
  name: pigo
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: pigo
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: pigo
          image: gcr.io/{{PROJECT_ID}}/pigo:{{VERSION}}
          env:
          - name: CASCADE_FILE
            value: "gs://khappygo/models/facefinder"

---

# Service pointing at the previous Deployment. This will be the target for event
# consumption.
  kind: Service
  apiVersion: v1
  metadata:
    name: pigo-service
  spec:
    selector:
      app: pigo
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

