apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotion
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: emotion
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: emotion
          image: gcr.io/{{PROJECT_ID}}/emotion:{{VERSION}}
          env:
          - name: MODEL
            value: "gs://khappygo/models/model.onnx"

---

# Service pointing at the previous Deployment. This will be the target for event
# consumption.
  kind: Service
  apiVersion: v1
  metadata:
    name: emotion-service
  spec:
    selector:
      app: emotion
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

